-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 添加背景图和热点字段到 profiles 表
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS background_url TEXT,
ADD COLUMN IF NOT EXISTS hot_points INTEGER DEFAULT 100,
ADD COLUMN IF NOT EXISTS heat_count INTEGER DEFAULT 0;

-- 更新 RLS 策略允许更新这些字段
CREATE POLICY "用户可以更新自己的完整资料" ON public.profiles
  FOR UPDATE USING (auth.uid() = id);