-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 管理员表
CREATE TABLE IF NOT EXISTS public.admins (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  email TEXT,
  role TEXT DEFAULT 'admin',
  is_active BOOLEAN DEFAULT true,
  last_login_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 帖子表
CREATE TABLE IF NOT EXISTS public.posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  title TEXT,
  content TEXT,
  cover_image TEXT,
  images TEXT[],
  tags TEXT[],
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'published', 'blocked', 'deleted')),
  is_ai_flagged BOOLEAN DEFAULT false,
  ai_flag_reason TEXT,
  hot_score INTEGER DEFAULT 0,
  view_count INTEGER DEFAULT 0,
  share_count INTEGER DEFAULT 0,
  likes INTEGER DEFAULT 0,
  comments INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 评论表
CREATE TABLE IF NOT EXISTS public.comments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id UUID REFERENCES public.posts(id) ON DELETE CASCADE,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  status TEXT DEFAULT 'published' CHECK (status IN ('pending', 'published', 'blocked', 'deleted')),
  is_ai_flagged BOOLEAN DEFAULT false,
  ai_flag_reason TEXT,
  parent_id UUID REFERENCES public.comments(id) ON DELETE CASCADE,
  likes INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 举报表
CREATE TABLE IF NOT EXISTS public.reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  reporter_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  target_type TEXT NOT NULL CHECK (target_type IN ('post', 'comment', 'user')),
  target_id UUID NOT NULL,
  reason TEXT NOT NULL,
  description TEXT,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'processed', 'ignored')),
  admin_id UUID REFERENCES public.admins(id) ON DELETE SET NULL,
  admin_note TEXT,
  processed_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 系统公告表
CREATE TABLE IF NOT EXISTS public.announcements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  is_pinned BOOLEAN DEFAULT false,
  is_active BOOLEAN DEFAULT true,
  admin_id UUID REFERENCES public.admins(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 话题标签表
CREATE TABLE IF NOT EXISTS public.tags (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT UNIQUE NOT NULL,
  description TEXT,
  is_active BOOLEAN DEFAULT true,
  requires_review BOOLEAN DEFAULT false,
  post_count INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 书卷表
CREATE TABLE IF NOT EXISTS public.books (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  religion TEXT NOT NULL,
  chapters INTEGER DEFAULT 0,
  description TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 经文表
CREATE TABLE IF NOT EXISTS public.scriptures (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  book_id UUID REFERENCES public.books(id) ON DELETE CASCADE,
  chapter INTEGER NOT NULL,
  verse INTEGER NOT NULL,
  content TEXT NOT NULL,
  translation TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 宗教百科表
CREATE TABLE IF NOT EXISTS public.religions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT UNIQUE NOT NULL,
  type TEXT NOT NULL,
  origin_place TEXT,
  origin_time TEXT,
  distribution TEXT,
  followers_scale TEXT,
  core_belief TEXT,
  introduction TEXT,
  history TEXT,
  doctrines TEXT,
  classics TEXT,
  festivals TEXT,
  rituals TEXT,
  taboos TEXT,
  sacred_sites TEXT,
  famous_figures TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 客服工单表
CREATE TABLE IF NOT EXISTS public.tickets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  subject TEXT NOT NULL,
  category TEXT NOT NULL,
  content TEXT NOT NULL,
  status TEXT DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')),
  priority TEXT DEFAULT 'normal' CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
  is_vip_priority BOOLEAN DEFAULT false,
  admin_id UUID REFERENCES public.admins(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  resolved_at TIMESTAMP
);

-- 工单回复表
CREATE TABLE IF NOT EXISTS public.ticket_replies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id UUID REFERENCES public.tickets(id) ON DELETE CASCADE,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  admin_id UUID REFERENCES public.admins(id) ON DELETE SET NULL,
  content TEXT NOT NULL,
  is_from_admin BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 违规词库表
CREATE TABLE IF NOT EXISTS public.banned_words (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  word TEXT UNIQUE NOT NULL,
  level TEXT DEFAULT 'medium' CHECK (level IN ('low', 'medium', 'high')),
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 审核日志表
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_id UUID REFERENCES public.admins(id) ON DELETE SET NULL,
  target_type TEXT NOT NULL,
  target_id UUID NOT NULL,
  action TEXT NOT NULL,
  reason TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 用户等级经验日志表
CREATE TABLE IF NOT EXISTS public.exp_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  action TEXT NOT NULL,
  exp_gained INTEGER NOT NULL,
  old_level INTEGER,
  new_level INTEGER,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 插入默认管理员账号
INSERT INTO public.admins (username, password_hash, email, role)
VALUES ('admin', crypt('admin123', gen_salt('bf')), 'admin@openfaith.com', 'super_admin')
ON CONFLICT (username) DO NOTHING;

-- 插入默认违规词
INSERT INTO public.banned_words (word, level) VALUES
('脏话', 'high'), ('广告', 'medium'), ('色情', 'high'), ('暴力', 'high')
ON CONFLICT (word) DO NOTHING;

-- 插入默认标签
INSERT INTO public.tags (name, description) VALUES
('基督教', '基督教相关内容'), ('伊斯兰教', '伊斯兰教相关内容'), ('佛教', '佛教相关内容'), ('犹太教', '犹太教相关内容'), ('印度教', '印度教相关内容')
ON CONFLICT (name) DO NOTHING;

-- 插入默认书卷
INSERT INTO public.books (name, religion, chapters, description) VALUES
('圣经', '基督教', 1189, '基督教经典，包含旧约和新约'), ('古兰经', '伊斯兰教', 114, '伊斯兰教唯一的根本经典'), ('佛经', '佛教', 5000, '佛教经典的总称')
ON CONFLICT DO NOTHING;

-- 插入默认宗教百科
INSERT INTO public.religions (name, type, origin_place, origin_time, distribution, followers_scale, core_belief, introduction) VALUES
('基督教', '一神教', '巴勒斯坦地区', '公元1世纪', '全球', '24亿', '信仰耶稣基督为救世主', '基督教是世界上最大的宗教之一')
ON CONFLICT (name) DO NOTHING;