-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE public.group_tag_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  tag_name TEXT NOT NULL,
  description TEXT,
  cover_image_url TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  reject_reason TEXT,
  reviewed_by UUID REFERENCES public.admins(id),
  reviewed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.group_tag_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "所有人可查看群聊标签申请" ON public.group_tag_requests FOR SELECT USING (true);
CREATE POLICY "登录用户可创建群聊标签申请" ON public.group_tag_requests FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "管理员可更新群聊标签申请" ON public.group_tag_requests FOR UPDATE USING (true);