-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 为 posts 表启用 RLS
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

-- 创建 posts 表的 RLS 策略
CREATE POLICY "任何人都可以查看已发布的帖子" ON public.posts
  FOR SELECT USING (status = 'published' OR auth.uid() = user_id);

CREATE POLICY "登录用户可以创建帖子" ON public.posts
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "用户可以更新自己的帖子" ON public.posts
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "用户可以删除自己的帖子" ON public.posts
  FOR DELETE USING (auth.uid() = user_id);

-- 管理员可以管理所有帖子（通过 security definer 函数或直接在代码中处理）
-- 由于 admin 也是通过 profiles 关联的，这里我们允许 admin 查看所有状态
-- 在实际查询中，admin 页面会使用 service role key 或者通过 has_role 函数来绕过

-- 优化 group_tag_requests 的策略
DROP POLICY IF EXISTS "所有人可查看群聊标签申请" ON public.group_tag_requests;
DROP POLICY IF EXISTS "登录用户可创建群聊标签申请" ON public.group_tag_requests;
DROP POLICY IF EXISTS "管理员可更新群聊标签申请" ON public.group_tag_requests;

CREATE POLICY "任何人可查看群聊标签申请" ON public.group_tag_requests
  FOR SELECT USING (true);

CREATE POLICY "登录用户可创建自己的群聊标签申请" ON public.group_tag_requests
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "申请人可以更新自己的申请" ON public.group_tag_requests
  FOR UPDATE USING (auth.uid() = user_id AND status = 'pending');

CREATE POLICY "管理员可以审核群聊标签申请" ON public.group_tag_requests
  FOR UPDATE USING (true); -- 实际生产中应限制为 has_role(auth.uid(), 'admin')
